# # Form implementation generated from reading ui file '/home/lbleier/cFS/tools/cFS-GroundSystem/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(552, 305)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(24*24)
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelHomeTitle = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(2)
        font.setBold(False)
        font.setWeight(5)
        self.labelHomeTitle.setFont(font)
        self.labelHomeTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelHomeTitle.setObjectName("labelHomeTitle")
        self.verticalLayout.addWidget(self.labelHomeTitle)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(141, 14))
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.comboBoxIpAddresses = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxIpAddresses.setMinimumSize(QtCore.QSize(132, 0))
        self.comboBoxIpAddresses.setMaximumSize(QtCore.QSize(132, 16777215))
        self.comboBoxIpAddresses.setObjectName("comboBoxIpAddresses")
        self.comboBoxIpAddresses.addItem("")
        self.gridLayout.addWidget(self.comboBoxIpAddresses, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0.01)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(169, 609))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.cbTlmHeaderVer = QtWidgets.QComboBox(self.centralwidget)
        self.cbTlmHeaderVer.setMinimumSize(QtCore.QSize(132, 0))
        self.cbTlmHeaderVer.setMaximumSize(QtCore.QSize(132, 16777215))
        self.cbTlmHeaderVer.setObjectName("cbTlmHeaderVer")
        self.cbTlmHeaderVer.addItem("")
        self.cbTlmHeaderVer.addItem("")
        self.cbTlmHeaderVer.addItem("")
        self.gridLayout.addWidget(self.cbTlmHeaderVer, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.sbTlmOffset = QtWidgets.QSpinBox(self.centralwidget)
        self.sbTlmOffset.setEnabled(False)
        self.sbTlmOffset.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbTlmOffset.setObjectName("sbTlmOffset")
        self.gridLayout.addWidget(self.sbTlmOffset, 1, 2, 1, 1)
        self.sbCmdOffsetPri = QtWidgets.QSpinBox(self.centralwidget)
        self.sbCmdOffsetPri.setEnabled(False)
        self.sbCmdOffsetPri.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbCmdOffsetPri.setObjectName("sbCmdOffsetPri")
        self.gridLayout.addWidget(self.sbCmdOffsetPri, 2, 2, 1, 1)
        self.cbCmdHeaderVer = QtWidgets.QComboBox(self.centralwidget)
        self.cbCmdHeaderVer.setObjectName("cbCmdHeaderVer")
        self.cbCmdHeaderVer.addItem("")
        self.cbCmdHeaderVer.addItem("")
        self.cbCmdHeaderVer.addItem("")
        self.gridLayout.addWidget(self.cbCmdHeaderVer, 2, 1, 1, 1)
        self.sbCmdOffsetSec = QtWidgets.QSpinBox(self.centralwidget)
        self.sbCmdOffsetSec.setEnabled(False)
        self.sbCmdOffsetSec.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sbCmdOffsetSec.setObjectName("sbCmdOffsetSec")
        self.gridLayout.addWidget(self.sbCmdOffsetSec, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(32)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonStartTlm = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartTlm.sizePolicy().hasHeightForWidth())
        self.pushButtonStartTlm.setSizePolicy(sizePolicy)
        self.pushButtonStartTlm.setObjectName("pushButtonStartTlm")
        self.horizontalLayout_2.addWidget(self.pushButtonStartTlm)
        self.pushButtonStartCmd = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStartCmd.sizePolicy().hasHeightForWidth())
        self.pushButtonStartCmd.setSizePolicy(sizePolicy)
        self.pushButtonStartCmd.setObjectName("pushButtonStartCmd")
        self.horizontalLayout_2.addWidget(self.pushButtonStartCmd)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(translate("MainWindow", "Main Window"))
        self.labelHomeTitle.setText(translate("MainWindow", "CFS Ground System"))
        self.label_3.setText(translate("MainWindow", "Selected IP Address"))
        self.comboBoxIpAddresses.setItemText(0, translate("MainWindow", "All"))
        self.label_4.setText(_translate("MainWindow", "Tlm header version"))
        self.cbTlmHeaderVer.setItemText(0, translate("MainWindow", "1"))
        self.cbTlmHeaderVer.setItemText(1, translate("MainWindow", "2"))
        self.cbTlmHeaderVer.setItemText(2, translate("MainWindow", "Custom"))
        self.label_2.setText(translate("MainWindow", "Cmd header version"))
        self.sbTlmOffset.setToolTip(translate("MainWindow", "<html><head/><body><p>Offset (in bytes) to be <span style=\" font-weight:600;\">added to</span> existing offsets listed in telemetry text files</p></body></html>"))
        self.sbCmdOffsetPri.setToolTip(translate("MainWindow", "<html><head/><body><p>Offset (in bytes) to be added <span style=\" font-weight:600;\">after</span> the <span style=\" font-weight:600;\">primary</span> header in a command packet</p></body></html>"))
        self.cbCmdHeaderVer.setItemText(0, translate("MainWindow", "1"))
        self.cbCmdHeaderVer.setItemText(1, translate("MainWindow", "2"))
        self.cbCmdHeaderVer.setItemText(2, translate("MainWindow", "Custom"))
        self.sbCmdOffsetSec.setToolTip(translate("MainWindow", "<html><head/><body><p>Offset (in bytes) to be added <span style=\" font-weight:600;\">after</span> the <span style=\" font-weight:600;\">secondary</span> header in a command packet</p></body></html>"))
        self.label_6.setText(translate("MainWindow", "(Hover for info)"))
        self.pushButtonStartTlm.setText(translate("MainWindow", "Stop Telemetry System"))
        self.pushButtonStartCmd.setText(_translate("MainWindow", "Stop Command System"))
        self.label_5.setText(_translate("MainWindow", "Read README.txt for help"))
        self.pushButton.setText(_translate("MainWindow", "Open README.txt"))

