# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file
# '/home/lbleier/cFS/tools/cFS-GroundSystem/Subsystems/cmdGui/GenericCommandDialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class UiGenericcommanddialog(object):
    def setupUi(self, generic_command_dialog):
        generic_command_dialog.setObjectName("GenericCommandDialog")
        generic_command_dialog.resize(549, 1058)
        self.vertical_layout_6 = QtWidgets.QVBoxLayout(generic_command_dialog)
        self.vertical_layout_6.setObjectName("verticalLayout_6")
        self.vertical_layout_4 = QtWidgets.QVBoxLayout()
        self.vertical_layout_4.setObjectName("verticalLayout_4")
        self.horizontal_layout = QtWidgets.QHBoxLayout()
        self.horizontal_layout.setObjectName("horizontalLayout")
        self.vertical_layout = QtWidgets.QVBoxLayout()
        self.vertical_layout.setObjectName("verticalLayout")
        self.sub_system_command_page_label = QtWidgets.QLabel(generic_command_dialog)
        self.sub_system_command_page_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_system_command_page_label.setObjectName("subSystemCommandPageLabel")
        self.vertical_layout.addWidget(self.sub_system_command_page_label)
        self.sub_system_line_edit = QtWidgets.QLineEdit(generic_command_dialog)
        self.sub_system_line_edit.setMinimumSize(QtCore.QSize(159, 31))
        self.sub_system_line_edit.setMaximumSize(QtCore.QSize(300, 31))
        self.sub_system_line_edit.setObjectName("subSystemLineEdit")
        self.vertical_layout.addWidget(self.sub_system_line_edit)
        self.horizontal_layout.addLayout(self.vertical_layout)
        self.vertical_layout_2 = QtWidgets.QVBoxLayout()
        self.vertical_layout_2.setObjectName("verticalLayout_2")
        self.packet_id_label = QtWidgets.QLabel(generic_command_dialog)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.packet_id_label.sizePolicy().hasHeightForWidth())
        self.packet_id_label.setSizePolicy(size_policy)
        self.packet_id_label.setMinimumSize(QtCore.QSize(0, 13))
        self.packet_id_label.setMaximumSize(QtCore.QSize(16777193, 13))
        self.packet_id_label.setObjectName("packetIdLabel")
        self.vertical_layout_2.addWidget(self.packet_id_label)
        self.packet_id = QtWidgets.QLCDNumber(generic_command_dialog)
        self.packet_id.setObjectName("packetId")
        self.vertical_layout_2.addWidget(self.packet_id)
        self.horizontal_layout.addLayout(self.vertical_layout_2)
        self.vertical_layout_3 = QtWidgets.QVBoxLayout()
        self.vertical_layout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(generic_command_dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.vertical_layout_3.addWidget(self.label_5)
        self.command_address_line_edit = QtWidgets.QLineEdit(generic_command_dialog)
        size_policy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.command_address_line_edit.sizePolicy().hasHeightForWidth())
        self.command_address_line_edit.setSizePolicy(size_policy)
        self.command_address_line_edit.setMinimumSize(QtCore.QSize(135, 31))
        self.command_address_line_edit.setMaximumSize(QtCore.QSize(135, 31))
        self.command_address_line_edit.setObjectName("commandAddressLineEdit")
        self.vertical_layout_3.addWidget(self.command_address_line_edit)
        self.horizontal_layout.addLayout(self.vertical_layout_3)
        spacer_item = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontal_layout.addItem(spacer_item)
        self.button_box = QtWidgets.QDialogButtonBox(generic_command_dialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("buttonBox")
        self.horizontal_layout.addWidget(self.button_box)
        self.vertical_layout_4.addLayout(self.horizontal_layout)
        self.label = QtWidgets.QLabel(generic_command_dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.vertical_layout_4.addWidget(self.label)
        self.tbl_commands = QtWidgets.QTableWidget(generic_command_dialog)
        self.tbl_commands.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_commands.setObjectName("tblCommands")
        self.tbl_commands.setColumnCount(2)
        self.tbl_commands.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_commands.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_commands.setHorizontalHeaderItem(1, item)
        self.tbl_commands.verticalHeader().setVisible(False)
        self.tbl_commands.verticalHeader().setMinimumSectionSize(40)
        self.vertical_layout_4.addWidget(self.tbl_commands)
        self.vertical_layout_6.addLayout(self.vertical_layout_4)

        self.retranslate_ui(generic_command_dialog)
        self.button_box.clicked['QAbstractButton*'].connect(generic_command_dialog.close)
        QtCore.QMetaObject.connectSlotsByName(generic_command_dialog)

    def retranslate_ui(self, generic_command_dialog):
        _translate = QtCore.QCoreApplication.translate
        generic_command_dialog.setWindowTitle(_translate("GenericCommandDialog", "Command Page"))
        self.sub_system_command_page_label.setText(_translate("GenericCommandDialog", "Subsystem"))
        self.packet_id_label.setText(_translate("GenericCommandDialog", "Packet ID"))
        self.label_5.setText(_translate("GenericCommandDialog", "Send To:"))
        self.label.setText(_translate("GenericCommandDialog", "Command"))
        item = self.tbl_commands.horizontalHeaderItem(0)
        item.setText(_translate("GenericCommandDialog", "Command"))
